apiVersion: v2
name: memcached
description: memcached chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: memcached
  version: 6.0.5
  repository: https://charts.bitnami.com/bitnami
